name: SnapEnhanceModGen Action

on:
  push:
    paths:
      - 'push-here-v2.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl
        shell: bash

      - name: Install unzip
        run: sudo apt-get install unzip -y

      - name: Install pup
        run: |
         wget https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip -O pup.zip
         unzip pup.zip
         chmod +x pup
         sudo mv pup /usr/local/bin/
        working-directory: . 

      - name: Grant execute permissions to script specific Version
        run: chmod +x scriptv.sh
        working-directory: .  

      - name: Run APK Download Script
        run: |
         ./scriptv.sh  
      
      
      - name: Run the command
        run: |
          java -jar lspatch.jar -m core.apk -f -l 2 -v snapv.apk

      - name: Rename Specific Version of Snapchat File
        run: mv snapv-360-lspatched.apk snapFirst.apk
     
      - name: Grant execute permissions to script latest version
        run: chmod +x script.sh
        working-directory: .  

      - name: Run APK Download Script
        run: |
         ./script.sh  
      
      
      - name: Run the command
        run: |
          java -jar lspatch.jar -m core.apk -f -l 2 -v snap.apk

      - name: Rename Specific Version of Snapchat File
        run: mv snap-360-lspatched.apk snapLatest.apk

      
      - name: Check if the release already exists
        id: check_release
        run: |
          RELEASE_VERSION=v0.1  # Change this to the initial release version
          if curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/releases/tags/$RELEASE_VERSION; then
            echo "Release $RELEASE_VERSION already exists."
            # Increment the release version
            RELEASE_VERSION=$(echo $RELEASE_VERSION | awk -F. '{$NF = $NF + 1;} 1' | sed 's/ /./')
          fi
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV

      - name: Create or Update Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            snapFirst.apk
            snapLatest.apk
          tag_name: ${{ env.RELEASE_VERSION }}
